language: python

python:
- '2.7'

# make use of vm's
sudo: 'required'


# have the docker service set up (we'll
# update it later)
services:
  - 'docker'

# prepare the machine before any code
# installation scripts
before_install:
  - '.travis/main.sh'

install:
- pip install -r requirements.txt

script:
- python -m unittest discover -v

before_install:
- openssl aes-256-cbc -K $encrypted_19ca236cca21_key -iv $encrypted_19ca236cca21_iv
  -in service-account.json.enc -out service-account.json -d

# first execute the test suite.
# after the test execution is done and didn't
# fail, build the images (if this step fails
# the whole Travis build is considered a failure).
script:
  - 'make test'
  - 'make image'

# only execute the following instructions in
# the case of a success (failing at this point
# won't mark the build as a failure).
# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD`
# filled you need to either use `travis`' cli
# and then `travis set ..` or go to the travis
# page of your repository and then change the
# environment in the settings pannel.
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u kvaid30 -p P@$$word ;
      make push-image ;
    fi

# don't notify me when things fail
notifications:
  email: false

deploy:
  provider: gae
  keyfile: "service-account.json"
  project: "simple-flask-application"
  config: "app.yml"
