language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python -m unittest discover -v
before_install:
- openssl aes-256-cbc -K $encrypted_1f1932773c11_key -iv $encrypted_1f1932773c11_iv
  -in service-account.json.enc -out service-account.json -d
