language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -t lib -r requirements.txt
script:
- python -m unittest discover -v
before_install:
- openssl aes-256-cbc -K $encrypted_19ca236cca21_key -iv $encrypted_19ca236cca21_iv
  -in service-account.json.enc -out service-account.json -d
deploy:
  provider: gae
  keyfile: "service-account.json"
  project: "simple-flask-application"
  config: "app.yml"
